#!/usr/bin/env python

from setuptools import setup, find_packages
import os
import subprocess

name = 'osccap'
version_py = os.path.join(os.path.dirname(__file__), 'osccap', 'version.py')


def git_pep440_version():
    full = subprocess.check_output(
            ['git', 'describe', '--tags', '--always', '--dirty=.dirty'],
            stderr=subprocess.STDOUT).decode().strip()
    tag = subprocess.check_output(
            ['git', 'describe', '--tags', '--always', '--abbrev=0'],
            stderr=subprocess.STDOUT).decode().strip()
    tail = full[len(tag):]
    return tag + tail.replace('-', '.dev', 1).replace('-', '+', 1)


try:
    version = git_pep440_version()
    with open(version_py, 'w') as f:
        f.write('# This file was autogenerated by setup.py\n')
        f.write('__version__ = \'%s\'\n' % (version,))
except (OSError, subprocess.CalledProcessError, IOError):
    try:
        with open(version_py, 'r') as f:
            d = dict()
            exec(f.read(), d)
            version = d['__version__']
    except IOError:
        version = 'unknown'


setup(name=name,
      version=version,
      description='Capture screenshot from digital oscilloscopes.',
      author_email='michael@walle.cc',
      options={
          'bdist_wininst': {'install_script': 'osccap_postinstall.py'},
          'bdist_msi': {'install_script': 'osccap_postinstall.py'},
      },
      install_requires=[
          'wxpython',
          'numpy'
      ],
      packages=find_packages(),
      package_data={'osccap': ['data/*.png', 'data/osccap.ico']},
      scripts=['osccap_postinstall.py'],
)
